### ISSUE TITLE
Formatting &nbsp; instead of space being pasted

### ISSUE THREAD

**Issue by cclambie** [Oluwasegun-AA/MultiClip#34]
**Describe the bug**
When I paste the clip it should past as: 
#note          ac:         co:       prop:      #note
Instead it is pasting as
#note&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ac:&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;co:&nbsp; &nbsp; &nbsp; &nbsp;prop:&nbsp; &nbsp; &nbsp; #note
![image](https://user-images.githubusercontent.com/877921/119885383-ae135900-bf29-11eb-8b96-0467fd4a6294.png)

**To Reproduce**
1. Go to MultiClip
2. Paste formatted text 
3. Press enter
4. Click "clip"
5. Paste from clipboard somewhere
6. See the "hidden" code values for space, line break and probably other formatting

**Expected behavior**
I would expect the pasted value to appear as formatted, or at least without the encoded formatting

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Brave/ Chromium
 - Version .24.86 Chromium: 90.0.4430.212 (Official Build) (64-bit)

**Comment by Oluwasegun-AA** [comment]
Thank you for raising this @cclambie. But this deviates from the intended use of this extension.
Multiclip returns the exact text as formatted when it was pasted. Interpreting encoded formatting in the text may compromise the data being stored.
With that said, I will proceed to close this issue. Thanks.

**Comment by cclambie** [comment]
Thanks for looking at this for me.
Maybe I wasn't clear.
The encoding is for correct storage yes.
But as per the screen shot, when recalling the stored content it should be exactly the same format as before. As you just said.
Hence the report.
The pasted format is with encoding, instead of the formatting that it represents...

**Comment by Oluwasegun-AA** [comment]
Thanks for shedding some light @cclambie.
This will be fixed immediately and will be deployed to version 0.5

Thank you.
